# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = Graphics


APP_CSRC	=	\
				Graphics.c \
				GraphicsBlit.c \
				TextRender.c  \
				VectorQuantization.c \
				ImageData.c  \
				GIF.c  \
#

include $(TOPDIR)/Makefile.include
