# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = Debug


APP_CSRC	=	\
				BoxPrintDebug.c  \
				DebugObservation.c  \
				Debug.c \
				Log.c \
				Monkey.c \
#

BOOT_CSRC	=	\
				Debug.c \
#

include $(TOPDIR)/Makefile.include
