# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = Input

COMMON_CSRC = \
				Input.c \
#

APP_CSRC	= $(COMMON_CSRC)
BOOT_CSRC	= $(COMMON_CSRC) 
GOOBER_CSRC = $(COMMON_CSRC)  


include $(TOPDIR)/Makefile.include
