# WebTV box rom subproject Makefile

TOPDIR = ../..
SUBDIR = Ansi

CommonCSources =	\
					chario.c \
					ctype.c \
					printf.c \
					str.c \
					strtol.c \
					strtoul.c \
					mem.c \
					sscanf.c \
					atoi.c \
#


APP_CSRC	= $(CommonCSources)
BOOT_CSRC	= $(CommonCSources)
GOOBER_CSRC = $(CommonCSources) 


include $(TOPDIR)/Makefile.include
