# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = Goober


GOOBER_CSRC =	\
				GooberBoot.c \
				GooberCStubs.c \
				GooberStubs.c \
				GooberUtils.c \
#

GOOBER_ASRC =	\

#


include $(TOPDIR)/Makefile.include
