# WebTV box rom subproject Makefile

TOPDIR = ../..
SUBDIR = pforth


GOOBER_CSRC =	\
				pf_c_glue.c \
                pf_compile.c \
                pf_core.c \
                pf_custom.c \
                pf_inner.c \
                pf_io.c \
                pf_mem.c \
                pf_save.c \
                pf_system.c \
                pf_text.c \
                pf_tools.c \
                pf_words.c \
#


include $(TOPDIR)/Makefile.include
