# WebTV box rom subproject Makefile

TOPDIR = ../..
SUBDIR = Crypto

APP_CSRC	=	\
				bn_add.c \
				bn_div.c \
				bn_exp.c \
				bn_gcd.c  \
				bn_lib.c \
				bn_mod.c \
				bn_mul.c \
				bn_mulw.c \
				bn_prime.c \
				bn_print.c \
				bn_rand.c \
				bn_shift.c \
				bn_sqr.c \
				bn_sub.c \
				bn_word.c \
				des.c \
				des_ncbc.c \
				des_set_key.c \
				digest.c \
				e_cbc_d.c \
				e_ecb_d.c \
				e_rc4.c \
				evp_enc.c \
				evp_err.c \
				m_md5.c \
				md5_dgst.c \
				md5_rand.c \
				rc4_enc.c \
				rsa_enc.c \
				rsa_gen.c \
				rsa_lib.c \
#

BOOT_CSRC	= \
#


include $(TOPDIR)/Makefile.include
