# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = Utilities

APP_CSRC =	\
			Utilities.c  \
			URLParser.c  \
			Cache.c  \
			CacheEntry.c \
			CacheStream.c \
			Stream.c  \
			List.c  \
			Linkable.c  \
			Region.c  \
			DateTime.c  \
#

include $(TOPDIR)/Makefile.include
