# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = Testing

APP_CSRC =	\
			Tourist.c \
			ClientTestANSI.c \
			ClientTest.c \
#

GOOBER_CSRC =\
			benchmarks.c \
#

include $(TOPDIR)/Makefile.include
