# WebTV box rom subproject Makefile

TOPDIR = ../..
SUBDIR = JPEG


APP_CSRC	=	\
				jpDecode.c  \
				jpDecodeMDU.c  \
				jpDrawing.c  \
				jpIDCT.c  \
				jpMarkers.c  \
				jpUtils.c  \
#


include $(TOPDIR)/Makefile.include
