# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = System

APP_CSRC =	\
			System.c  \
			SystemVersion.c  \
			Clock.c \
#


SystemVersion.c	: ../Interfaces/SystemVersion.h


include $(TOPDIR)/Makefile.include
