# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = HTML


APP_CSRC	=	\
				Anchor.c  \
				Animation.c  \
				AudioScope.c  \
				Cell.c  \
				Code.c  \
				ClientFunctions.c  \
				Displayable.c  \
				Document.c  \
				DocumentBuilder.c  \
				Form.c  \
				Image.c  \
				ImageMap.c  \
				Page.c  \
				Parser.c  \
				Table.c  \
				Tag.c  \
				Text.c  \
				Song.c  \
#
#				Embedded.c  \


include $(TOPDIR)/Makefile.include
