/* ===========================================================================
	Classes.h
	
	Copyright (c) 1995-1996 Artemis Research, Inc. All rights reserved.
=========================================================================== */

#ifndef __CLASSES_H__
#define __CLASSES_H__

// Don't forget to add new classes to DebugClassNumberToName(ClassNumber class)
// 		which is found in Debug.c until we automate it.

enum ClassNumber
{
	kNoClassNumber = 0,
	kClassNumberXPoint = 1,
	kClassNumberSystem = 2,
	kClassNumberDataStream = 3,
	kClassNumberRecentURL = 4,
	kClassNumberResourceDataCache = 5,
	kClassNumberText = 6,
	kClassNumberSelector = 7,
	kClassNumberSelectable = 8,
	kClassNumberScreen = 9,
	kClassNumberContentView = 10,
	kClassNumberPage = 11,
	kClassNumberMacSimulator = 12,
	kClassNumberLinkable = 13,
	kClassNumberLayer = 14,
	kClassNumberImageData = 15,
	kClassNumberURLParser = 16,
	kClassNumberRecentPanel = 17,
	kClassNumberStatusIndicator = 18,
	kClassNumberHandlesInput = 19,
	kClassNumberDataList = 21,
	kClassNumberResource = 22,
	kClassNumberGIFResource = 23,
	kClassNumberTCPStream = 24,
	kClassNumberStream = 25,
	kClassNumberSocket = 26,
	kClassNumberQueue = 27,
	kClassNumberProtocol = 28,
	kClassNumberRegion = 29,
	kClassNumberHTTPProtocol = 30,
	kClassNumberCheckBox = 31,
	kClassNumberHasIterator = 32,
	kClassNumberIterator = 33,
	kClassNumberDataIterator = 34,
	kClassNumberStoreStream = 35,
	kClassNumberFileStream = 36,
	kClassNumberWTVProtocol = 37,
	kClassNumberGIF = 38,
	kClassNumberMemoryStream = 39,
	kClassNumberFileProtocol = 40,
	kClassNumberJPEGResource = 41,
	kClassNumberStoreProtocol = 42,
	kClassNumberAnimationResource = 43,
	kClassNumberSystemLogo = 44,
	kClassNumberPageViewer = 45,
	kClassNumberControl = 46,
	kClassNumberLoginProtocol = 47,
	kClassNumberNetwork = 48,
	kClassNumberCell = 49,
	kClassNumberObjectList = 50,
	kClassNumberTextField = 51,
	kClassNumberCacheStream = 52,
	kClassNumberCheckbox = 53,
	kClassNumberRadioButton = 54,
	kClassNumberDateTimeParser = 55,
	kClassNumberStringList = 56,
	kClassNumberBorderImageResource = 57,
	kClassNumberBitMapResource = 58,
	kClassNumberBitMapImage = 59,
	kClassNumberAlertWindow = 60,
	kClassNumberCache = 61,
	kClassNumberCacheEntry = 62,
	kClassNumberCacheReader = 63,
	kClassNumberCacheWriter = 64,
	kClassNumberAlignment = 65,
	kClassNumberAnchor = 66,
	kClassNumberAnchorEnd = 67,
	kClassNumberAnchorRegion = 68,
	kClassNumberBullet = 69,
	kClassNumberCompositeDisplayable = 70,
	kClassNumberDefinitionMargin = 71,
	kClassNumberDisplayable = 72,
	kClassNumberDocument = 73,
	kClassNumberDocumentBuilder = 74,
	kClassNumberForm = 75,
	kClassNumberImage = 76,
	kClassNumberButton = 77,
	kClassNumberInputHidden = 78,
	kClassNumberInputImage = 79,
	kClassNumberInputPassword = 80,
	kClassNumberResetButton = 81,
	kClassNumberMenu = 82,
	kClassNumberSubmitButton = 83,
	kClassNumberLineBreak = 84,
	kClassNumberMargin = 85,
	kClassNumberMenuItem = 86,
	kClassNumberTag = 87,
	kClassNumberHTMLParser = 88,
	kClassNumberDivider = 89,
	kClassNumberSpatialDisplayable = 90,
	kClassNumberTable = 91,
	kClassNumberService = 92,
	kClassNumberKeyboard = 93,
	kClassNumberOptionsPanel = 94,
	kClassNumberAnimationImage = 95,
	kClassNumberBorderImage = 96,
	kClassNumberGIFImage = 97,
	kClassNumberJPEGImage = 98,
	kClassNumberOldCelImage = 99,
	kClassNumberEmbedded = 100,
	kClassNumberSong = 101,
	kClassNumberSongData = 102,
	kClassNumberMIDI = 103,
	kClassNumberForegroundView = 104,
	kClassNumberObjectIterator = 105,
	kClassNumberClock = 106,
	kClassNumberInfoPanel = 107,
	kClassNumberImageMap = 108,
	kClassNumberArea = 109,
	kClassNumberParser = 110,
	kClassNumberImageMapParser = 111,
	kClassNumberBuilder = 112,
	kClassNumberImageMapBuilder = 113,
	kClassNumberPanel = 114,
	kClassNumberStringDictionary = 115,
	kClassNumberFidoCelRecord = 116,
	kClassNumberFidoCelArrayPool = 117,
	kClassNumberFidoCompatibilityState = 118,
	kClassNumberFidoClutBlockList = 119,
	kClassNumberImageMapSelectable = 120,
	kClassNumberBackURL = 121,
	kClassNumberNewCelImage = 122,
	kClassNumberFidoFillBlockList = 123,
	kClassNumberFidoTexture = 124,
	kClassNumberClockField = 125,
	kClassNumberMenuLayer = 126,
	kClassNumberServiceList = 127,
	kClassNumberColorText = 128,
	kClassNumberColorBullet = 129,
	kClassNumberTagList = 130,
	kClassNumberTinySocket = 131,
	kClassNumberServicePointer = 132,
	kClassNumberPrefetchBuilder = 133,
	kClassNumberDocumentPrefetcher = 134,
	kClassNumberSplashWindow = 135,
	kClassNumberHTTPGetCommand = 136,
	kClassNumberHTTPPostCommand = 137,
	kClassNumberWTVPGetCommand = 138,
	kClassNumberWTVPPostCommand = 139,
	kClassNumberMPEGAudioStream = 140,
	kClassNumberProtocolCommand = 141,
	kClassNumberHTTPCommand = 142,
	kClassNumberWTVPCommand = 143,
	kClassNumberPlainTextParser = 144,
	kClassNumberSynthesisFilter = 145,
	kClassNumberMacSocket = 146,
	kClassNumberConnectWindow = 147,
	kClassNumberSelectionLayer = 148,
	kClassNumberSideBar = 149,
	kClassNumberImageMapCursor = 151,
	kClassNumberTouristSite = 152,
	kClassNumberTouristSiteListIterator = 153,
	kClassNumberTouristJournal = 154,
	kClassNumberTouristJournalIterator = 155,
	kClassNumberTouristItinerary = 156,
	kClassNumberTouristItineraryIterator = 157,
	kClassNumberTourist = 158,
	kClassNumberLoginPanel = 159,
	kClassNumberXBitMapImage = 160,
	kClassNumberVectorQuantizer = 161,
	kClassNumberAnimation = 162,
	kClassNumberFidoCelPoolLink = 163,
	kClassNumberFidoYPoolLink = 164,
	kClassNumberFidoYEntryContainer = 165,
	kClassNumberFidoYEntry = 166,
	kClassNumberFidoImage= 167,
	kClassNumberConnectIndicator = 168,
	kClassNumberRealAudioStream = 169,
	kClassNumberCRaSession = 170,
	kClassNumberCookieList = 171,
	kClassNumberCode = 172,
	kClassNumberVisitedURL = 173,
	kClassNumberVisitedList = 174,
	//kClassNumber = 175,
	//kClassNumber = 176,
	//kClassNumber = 177,
	//kClassNumber = 178,
	//kClassNumber = 179,
	//kClassNumber = 180,
	//kClassNumber = 181,
	kClassNumberGenericAlertWindow = 182,
	kClassNumberSecureSocket = 183,	
	kClassNumberMIDISong = 184,	
	kClassNumberSoundEffect = 185,	
	kClassNumberPopUpMenu = 186,
	kClassNumberScrollingList = 187,
	kClassNumberPowerOffAlert = 188,
	kClassNumberRC4Stream = 189,
	kClassNumberAuthorizationList = 190,
	kClassNumberAudioScope = 191,
	kMaxClassNumber = 191
};
typedef enum ClassNumber ClassNumber;

#ifdef __cplusplus
extern "C" {
#endif

#if defined(DEBUG_CLASSNUMBER) || defined(MEMORY_TRACKING)
const char* DebugClassNumberToName(ClassNumber c);		// located in Debug.c
#endif /* defined(DEBUG_CLASSNUMBER) || defined(MEMORY_TRACKING) */

#ifdef __cplusplus
}
#endif

#else
	#ifdef FIND_MULTIPLY_INCLUDED_HEADERS
	#error "Attempted to #include Classes.h multiple times"
	#endif
#endif /* __CLASSES_H__ */
