# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = Communications


APP_CSRC	=	\
				Authorization.c \
				Cookie.c  \
				HTTP.c \
				Protocol.c \
				Serial.c  \
				Service.c  \
				Socket.c  \
				TinySocket.c \
				Resource.c  \
				Network.c  \
				WTVProtocol.c \
#

BOOT_CSRC	=	\
				Serial.c  \
#


include $(TOPDIR)/Makefile.include
