# WebTV box rom subproject Makefile

TOPDIR = ../..
SUBDIR = MIDI

APP_CSRC = \
			AudioStream.c \
			DriverTools.c \
			GenMacTools.c \
			GenOutput.c  \
			GenPatch.c   \
			GenReverb.c  \
			GenSeq.c     \
			GenSetup.c   \
			GenSong.c    \
			GenSynthFilters.c    \
			GenSynthInterp2.c    \
			NewNewLZSS.c   		 \
			SampleTools.c    \
			SMOD_Volume_Scaler.c    \
			X_API.c    			\
			GenSynth.c   \
			MIDI.c   \
#

include $(TOPDIR)/Makefile.include
