# WebTV box rom subproject Makefile

TOPDIR = ..
SUBDIR = UserInterface

APP_CSRC =	\
			AlertWindow.c  \
			Button.c  \
			ClockField.c  \
			ContentView.c  \
			Control.c  \
			Keyboard.c  \
			InfoPanel.c  \
			Layer.c  \
			LoginPanel.c  \
			Menu.c  \
			OptionsPanel.c \
			PageViewer.c  \
			Panel.c  \
			RadioButton.c  \
			RecentPanel.c \
			Screen.c  \
			SetUIElement.c  \
			Status.c  \
			SystemLogo.c  \
			TextField.c  \
#

include $(TOPDIR)/Makefile.include
