# WebTV box rom subproject Makefile

TOPDIR = ../../..
SUBDIR = Tiny


APP_CSRC	=	\
				TinyDNR.c \
				ppp.c \
				tinytcp.c \
				tinyip.c \
				tinyudp.c \
#
		
BOOT_CSRC	=	\
				ppp.c \
				tinytcp.c \
				tinyip.c \
				tinyudp.c \
#


include $(TOPDIR)/Makefile.include
