# WebTV box rom subproject Makefile

TOPDIR = ../..
SUBDIR = Tellyscript


APP_CSRC	= 	\
				FormatString.c  \
				Interpreter.c  \
				Intrinsic.c  \
				scanner.c  \
				TellyIO.c  \
#
		
BOOT_CSRC	= 	\
				FormatString.c  \
				Interpreter.c  \
				Intrinsic.c  \
				scanner.c  \
				TellyIO.c  \
#

include $(TOPDIR)/Makefile.include
